export default defineAppConfig({
  nuxtIcon: {
    aliases: {
      spinner: 'ph:spinner-gap',
      light: 'ph:sun-duotone',
      dark: 'ph:moon-duotone',
      system: 'ph:circle-half-duotone',
      nuxt: 'logos:nuxt-icon',
      vite: 'logos:vitejs',
      unocss: 'logos:unocss',
      headless: 'logos:headlessui-icon',
      vercel: 'akar-icons:vercel-fill',
      metamask: 'logos:metamask-icon',
      ethereum: 'logos:ethereum',
      arbitrum: 'IconArbitrum',
      optimism: 'IconOptimism',
      polygon: 'IconPolygon',
      sksync: 'IconZkSync',
      gnosis: 'IconGnosis',
      plus: 'ph:plus',
      cross: 'ph:x',
      menu: 'ph:dots-three-outline',
      dropdown: 'ph:caret-down',
      gas: 'ph:gas-pump-duotone',
    },
  },
})
