export default defineAppConfig({
  unocss: {
    uno: true,
    attributify: true,
    shortcuts: {
      'bg-base': 'bg-zinc-100 dark:bg-zinc-800',
    },
  },
  nuxtIcon: {
    aliases: {
      nuxt: 'logos:nuxt-icon',
      vite: 'logos:vitejs',
      windi: 'vscode-icons:file-type-windi',
      vercel: 'akar-icons:vercel-fill',
      github: 'carbon:logo-github',
      javascript: 'logos:javascript',
      ethereum: 'logos:ethereum',
      pytorch: 'logos:pytorch-icon',
      twitter: 'logos:twitter',
      discord: 'logos:discord-icon',
      reddit: 'logos:reddit-icon',
      youtube: 'logos:youtube-icon',
      'search-console': 'logos:google-search-console',
      'google-analytics': 'logos:google-analytics',
      sentry: 'simple-icons:sentry',
      plausible: 'IconPlausible',
      linear: 'simple-icons:linear',
      spinner: 'ph:spinner-gap',
      refresh: 'ph:arrows-clockwise-fill',
      light: 'ph:sun',
      dark: 'ph:moon',
      system: 'ph:circle-half',
      star: 'ph:star-bold',
      fork: 'ph:git-fork-bold',
      commit: 'ph:git-commit-bold',
      issue: 'ph:warning-circle-bold',
      pr: 'ph:git-pull-request-bold',
      contributors: 'ph:users-bold',
      package: 'ph:package-bold',
      release: 'ic:outline-new-releases',
      collection: 'ph:folder',
      collections: 'ph:folders',
      project: 'carbon:dashboard',
      info: 'mdi:information-variant',
      plus: 'ph:plus',
      cross: 'ph:x-bold',
      edit: 'ph:pencil-line-duotone',
      experimental: 'ph:flask-duotone',
      handle: 'ic:round-drag-handle',
      check: 'ph:check',
      'file-search': 'ph:file-search',
    },
  }
})
